- hosts: servers
  tasks:
    - set_fact:
        was_accessible: "up"

    - meta: clear_host_errors
    - debug:
        msg: "Hello"

    - when:
        - was_accessible is defined
      debug:
        msg: "Hello again, I am up."
